// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// TodosCreate implements Todos_create operation.
//
// Create a Todo.
//
// POST /todos
func (UnimplementedHandler) TodosCreate(ctx context.Context, req *Todo) (r *Todo, _ error) {
	return r, ht.ErrNotImplemented
}

// TodosDelete implements Todos_delete operation.
//
// Delete a Todo.
//
// DELETE /todos/{id}
func (UnimplementedHandler) TodosDelete(ctx context.Context, params TodosDeleteParams) error {
	return ht.ErrNotImplemented
}

// TodosList implements Todos_list operation.
//
// List todos.
//
// GET /todos
func (UnimplementedHandler) TodosList(ctx context.Context) (r *TodoList, _ error) {
	return r, ht.ErrNotImplemented
}

// TodosRead implements Todos_read operation.
//
// Read todos.
//
// GET /todos/{id}
func (UnimplementedHandler) TodosRead(ctx context.Context, params TodosReadParams) (r *Todo, _ error) {
	return r, ht.ErrNotImplemented
}

// TodosUpdate implements Todos_update operation.
//
// Update a Todo.
//
// PATCH /todos/{id}
func (UnimplementedHandler) TodosUpdate(ctx context.Context, req *TodoUpdate, params TodosUpdateParams) (r *Todo, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
