// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	TodosAnalyzeOperation OperationName = "TodosAnalyze"
	TodosCreateOperation  OperationName = "TodosCreate"
	TodosDeleteOperation  OperationName = "TodosDelete"
	TodosListOperation    OperationName = "TodosList"
	TodosReadOperation    OperationName = "TodosRead"
	TodosUpdateOperation  OperationName = "TodosUpdate"
)
